/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

import TwinPrimes.LinearRoots
import Mathlib.Analysis.Normed.Ring.Lemmas
import Mathlib.Algebra.Order.Ring.Star
import Mathlib.Data.Int.Star
import Mathlib.Tactic

/-!
# Finiteness of Sieve Collisions for Twin Primes

This file formalizes the collision analysis for the twin prime sieve: for a fixed `k`-tuple
of distinct integer shifts `h`, collisions between the excluded residue classes of distinct
shifts modulo a prime `p` can only occur when `p` divides one of the "collision values"
`hᵢ - hⱼ`, `hᵢ - hⱼ + 2`, or `hᵢ - hⱼ - 2`.

An admissible `k`-tuple must satisfy `hᵢ - hⱼ ∉ {0, 2, -2}` for all `i ≠ j`. This
ensures that no forced collisions exist and that the excluded class count reaches `2k`
for sufficiently large primes.

## Main Results

* `TwinPrimes.collision_condition`: The collision classification.
* `TwinPrimes.excludedClasses_card_maximal`: `|S_p(h)| = 2k` for large odd `p`.

## References

* [A. Granville, P. Kurlberg, *Poisson statistics via the Chinese remainder theorem*]
  [arXiv:math/0412135v2]
-/

open Finset BigOperators

namespace TwinPrimes

variable {p : ℕ} [hp : Fact p.Prime]

private instance : NeZero p := ⟨hp.out.ne_zero⟩

/-! ### Admissibility -/

/-- A `k`-tuple of integer shifts `h` is admissible for the twin prime sieve if for all
`i ≠ j`, `hᵢ - hⱼ ∉ {0, 2, -2}`. Equivalently, the shifts are distinct and no two
shifts differ by exactly 2. -/
def Admissible {k : ℕ} (h : Fin k → ℤ) : Prop :=
  ∀ i j, i ≠ j → h i - h j ≠ 0 ∧ h i - h j ≠ 2 ∧ h i - h j ≠ -2

/-- An admissible tuple has injective shifts. -/
theorem Admissible.injective {k : ℕ} {h : Fin k → ℤ} (hadm : Admissible h) :
    Function.Injective h := by
  intro i j hij
  by_contra h_ne
  exact (hadm i j h_ne).1 (sub_eq_zero_of_eq hij)

/-! ### The collision condition -/

/-- **Collision classification.** If two excluded classes from shifts `a` and `b` coincide
in `ZMod p`, then `a = b`, `a - b = 2`, or `a - b = -2` in `ZMod p`. -/
theorem collision_condition {a b : ZMod p}
    (hcoll : -a = -b ∨ -a = -2 - b ∨ (-2 : ZMod p) - a = -b ∨
             (-2 : ZMod p) - a = -2 - b) :
    a = b ∨ (a - b : ZMod p) = 2 ∨ (a - b : ZMod p) = -2 := by
  grind +qlia

end TwinPrimes

/-- For `|d| < p` and `d ≠ 0`, `p ∤ d`. -/
theorem TwinPrimes.not_dvd_of_natAbs_lt {p : ℕ} {d : ℤ} (hd : d ≠ 0) (hlt : d.natAbs < p) :
    ¬((p : ℤ) ∣ d) := by
  intro ⟨k, hk⟩
  exact absurd (Nat.le_of_dvd (Int.natAbs_pos.mpr hd) (Int.natCast_dvd.mp ⟨k, hk⟩)) (not_le.mpr hlt)

namespace TwinPrimes

variable {p : ℕ} [hp : Fact p.Prime]

private instance : NeZero p := ⟨hp.out.ne_zero⟩

/-! ### Excluded classes are disjoint for large primes -/

/-- For a prime `p ≥ 3`, the excluded classes generated by a single shift `a` are
`{-a, -2 - a}` and have cardinality 2. -/
theorem single_shift_excluded_card (hp2 : p ≠ 2) (a : ZMod p) :
    ({-a, (-2 : ZMod p) - a} : Finset (ZMod p)).card = 2 := by
  rw [Finset.card_pair]
  simp +zetaDelta at *
  rw [eq_sub_iff_add_eq]; norm_num
  erw [ZMod.natCast_eq_zero_iff]
  exact Nat.not_dvd_of_pos_of_lt (by decide) (lt_of_le_of_ne hp.1.two_le (Ne.symm hp2))

/-
The excluded classes for a k-tuple decompose as a union of pairs.
-/
theorem excludedClasses_eq_biUnion {k : ℕ} (h : Fin k → ZMod p) :
    excludedClasses p h =
      Finset.biUnion Finset.univ
        (fun i => {-(h i), (-2 : ZMod p) - h i}) := by
  ext x; simp [excludedClasses];
  grind +locals

/-
**Main collision finiteness result.**
For an admissible `k`-tuple of integer shifts `h`, the number of distinct excluded
residue classes modulo an odd prime `p` is exactly `2k` whenever `p` exceeds
the collision threshold.
-/
theorem excludedClasses_card_maximal {k : ℕ} {h : Fin k → ℤ}
    (hp2 : p ≠ 2)
    (hadm : Admissible h)
    (hp_large : collisionThreshold h < p) :
    (excludedClasses p (fun i => (h i : ZMod p))).card = 2 * k := by
  rw [ excludedClasses_eq_biUnion, Finset.card_biUnion ];
  · rw [ Finset.sum_congr rfl fun _ _ => single_shift_excluded_card hp2 _, Finset.sum_const, Finset.card_fin, smul_eq_mul, mul_comm ];
  · intros i hi j hj hij; contrapose! hij; simp_all +decide [ Finset.disjoint_left ] ;
    by_cases hi : ( h i : ZMod p ) = h j <;> by_cases hj : - ( h i : ZMod p ) = -2 - h j <;> simp_all +decide [ sub_eq_iff_eq_add ];
    · norm_num [ neg_eq_iff_add_eq_zero ] at hj;
      rcases p with ( _ | _ | _ | p ) <;> cases hj <;> trivial;
    · have h_div : (p : ℤ) ∣ (h i - h j) := by
        simpa [ ← ZMod.intCast_zmod_eq_zero_iff_dvd ] using sub_eq_zero.mpr hi;
      contrapose! hp_large;
      refine' le_trans _ ( Finset.le_sup ( f := fun ij : Fin k × Fin k => Max.max ( Int.natAbs ( h ij.1 - h ij.2 ) ) ( Max.max ( Int.natAbs ( h ij.1 - h ij.2 + 2 ) ) ( Int.natAbs ( h ij.1 - h ij.2 - 2 ) ) ) ) ( Finset.mk_mem_product ( Finset.mem_univ i ) ( Finset.mem_univ j ) ) );
      exact Nat.le_of_dvd ( Int.natAbs_pos.mpr ( sub_ne_zero_of_ne <| by intro h; have := hadm i j hp_large; aesop ) ) ( Int.natCast_dvd.mp h_div ) |> le_trans <| le_max_left _ _;
    · have h_div : (p : ℤ) ∣ (h i - h j - 2) := by
        simp_all +decide [ ← ZMod.intCast_zmod_eq_zero_iff_dvd, sub_eq_iff_eq_add ];
        linear_combination -hj;
      have h_abs : Int.natAbs (h i - h j - 2) < p := by
        refine' lt_of_le_of_lt _ hp_large;
        exact Finset.le_sup ( f := fun ij : Fin k × Fin k => Max.max ( Int.natAbs ( h ij.1 - h ij.2 ) ) ( Max.max ( Int.natAbs ( h ij.1 - h ij.2 + 2 ) ) ( Int.natAbs ( h ij.1 - h ij.2 - 2 ) ) ) ) ( Finset.mk_mem_product ( Finset.mem_univ i ) ( Finset.mem_univ j ) ) |> le_trans ( by simp +decide );
      exact absurd h_abs ( by linarith [ Int.le_of_dvd ( abs_pos.mpr ( show h i - h j - 2 ≠ 0 from fun h => by have := hadm i j; simp_all +decide [ sub_eq_iff_eq_add ] ) ) ( by simpa [ ← Int.natCast_dvd_natCast ] using h_div ) ] );
    · -- Since $p$ divides $h_i - h_j + 2$, we have $|h_i - h_j + 2| \geq p$.
      have h_abs : Int.natAbs (h i - h j + 2) ≥ p := by
        exact Nat.le_of_dvd ( Int.natAbs_pos.mpr ( show h i - h j + 2 ≠ 0 from fun h => by have := hadm i j ( by aesop ) ; omega ) ) ( Int.natCast_dvd.mp <| by simpa [ ← ZMod.intCast_zmod_eq_zero_iff_dvd ] using by linear_combination' hij.symm );
      exact absurd h_abs ( not_le_of_gt ( lt_of_le_of_lt ( Finset.le_sup ( f := fun ij : Fin k × Fin k => Max.max ( Int.natAbs ( h ij.1 - h ij.2 ) ) ( Max.max ( Int.natAbs ( h ij.1 - h ij.2 + 2 ) ) ( Int.natAbs ( h ij.1 - h ij.2 - 2 ) ) ) ) ( Finset.mk_mem_product ( Finset.mem_univ i ) ( Finset.mem_univ j ) ) |> le_trans ( le_max_of_le_right <| le_max_left _ _ ) ) hp_large ) )

end TwinPrimes
