/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

import NearSquarePrimes.QuadraticRoots
import Mathlib.Analysis.Normed.Ring.Lemmas
import Mathlib.Algebra.Order.Ring.Star
import Mathlib.Data.Int.Star
import Mathlib.Tactic

/-!
# Finiteness of Sieve Collisions (Lemma 1)

This file formalizes Lemma 1 of the manuscript: the finiteness of collisions between
excluded residue classes in the `n² + 1` sieve.

For a fixed `k`-tuple of distinct even integers `h`, collisions between the excluded
classes of distinct shifts `hᵢ` and `hⱼ` modulo a prime `p ≡ 1 (mod 4)` can only
occur when `p ∣ (hᵢ - hⱼ)` or `p ∣ ((hᵢ - hⱼ)² + 4)`.

## Main Results

* `NearSquarePrimes.cross_collision_dvd`: The Diophantine collision criterion.
* `NearSquarePrimes.collision_condition`: Full collision characterization.
* `NearSquarePrimes.no_collision_of_large_prime_dvd`: Large primes avoid collisions.
* `NearSquarePrimes.excludedClasses_card_maximal`: `|S_p(h)| = 2k` for large `p`.

## References

* Portela, F. (2026). *A Poisson Limit Model for Landau's First Problem via
  Bounded-Variance Multi-Residue Sieves*, Lemma 1.
-/

open Finset BigOperators

namespace NearSquarePrimes

variable {p : ℕ} [hp : Fact p.Prime]

private instance : NeZero p := ⟨hp.out.ne_zero⟩

/-! ### The collision condition -/

/-
**Cross-collision criterion.** Let `ν` be a root of `x² + 1 ≡ 0 (mod p)`.
If the excluded class `ν - a` coincides with `-ν - b` modulo `p`,
then `(a - b)² + 4 ≡ 0 (mod p)` in `ZMod p`.

Proof: `ν - a = -ν - b` gives `2ν = a - b`, so `4ν² = (a-b)²`.
Since `ν² = -1`, we get `(a-b)² = -4`, hence `(a-b)² + 4 = 0`.
-/
theorem cross_collision_sq_add_four {ν a b : ZMod p}
    (hν : ν ^ 2 + 1 = 0)
    (hcoll : ν - a = -ν - b) :
    (a - b) ^ 2 + 4 = (0 : ZMod p) := by
  grind +qlia

/-
**Collision classification.** If some excluded class of shift `a` coincides with
some excluded class of shift `b`, then either `a = b` or `(a - b)² + 4 = 0` in
`ZMod p`. The four possible collision types are:
1. `ν - a = ν - b` ⟹ `a = b`
2. `ν - a = -ν - b` ⟹ `(a-b)² + 4 = 0`
3. `-ν - a = ν - b` ⟹ `(a-b)² + 4 = 0`
4. `-ν - a = -ν - b` ⟹ `a = b`
-/
theorem collision_condition {ν a b : ZMod p}
    (_hp2 : p ≠ 2)
    (hν : ν ^ 2 + 1 = 0)
    (hcoll : ν - a = ν - b ∨ ν - a = -ν - b ∨ -ν - a = ν - b ∨ -ν - a = -ν - b) :
    a = b ∨ (a - b) ^ 2 + 4 = (0 : ZMod p) := by
  grind +splitImp

/-
For a prime `p` with `(d² + 4 : ℤ) < p` and `d ≠ 0`, neither
`p ∣ d` nor `p ∣ (d² + 4)` holds. Hence no collisions can occur.
-/
theorem no_collision_of_large_prime_dvd {d : ℤ} (hd : d ≠ 0)
    (hp_large : (d ^ 2 + 4).natAbs < p) :
    ¬((p : ℤ) ∣ d) ∧ ¬((p : ℤ) ∣ d ^ 2 + 4) := by
  constructor <;> rintro ⟨ k, hk ⟩;
  · rcases k with ( ⟨ _ | _ | k ⟩ | ⟨ _ | _ | k ⟩ ) <;> simp_all +decide;
    · nlinarith [ abs_of_nonneg ( by positivity : 0 ≤ ( p : ℤ ) ^ 2 + 4 ) ];
    · rw [ ← Int.ofNat_lt, Int.natAbs_of_nonneg ( by positivity ) ] at hp_large ; nlinarith [ hp.1.two_le, mul_pos hp.1.pos ( Nat.succ_pos k ) ];
    · nlinarith [ abs_of_nonneg ( by positivity : 0 ≤ ( p : ℤ ) ^ 2 + 4 ) ];
    · nlinarith [ abs_of_nonneg ( by positivity : 0 ≤ ( p * 2 : ℤ ) ^ 2 + 4 ) ];
    · norm_num [ Int.negSucc_eq, sq, mul_assoc ] at *;
      rw [ ← Int.ofNat_lt, Int.natAbs_of_nonneg ] at hp_large <;> nlinarith [ hp.1.two_le, mul_pos hp.1.pos ( Nat.succ_pos k ) ];
  · cases abs_cases ( d ^ 2 + 4 ) <;> nlinarith [ show k = 0 by nlinarith ]

/-! ### Excluded classes are disjoint for large primes -/

/-
For a prime `p > 2` and a root `ν` of `x² + 1 ≡ 0`, the excluded classes
`{ν - a, -ν - a}` generated by a single shift `a` have cardinality 2.
-/
theorem single_shift_excluded_card {ν : ZMod p} (hp2 : p ≠ 2)
    (hν : ν ^ 2 + 1 = 0) (a : ZMod p) :
    ({ν - a, -ν - a} : Finset (ZMod p)).card = 2 := by
  rw [ Finset.card_pair ];
  exact fun h => sqrtNegOne_ne_neg hp2 hν <| by linear_combination' h;

/-
**Main finiteness result (Lemma 1 of the manuscript).**
For a `k`-tuple of distinct integer shifts `h`, the number of distinct excluded
residue classes modulo a prime `p ≡ 1 (mod 4)` is exactly `2k` whenever `p` exceeds
the collision threshold `P(h) = max_{i,j} ((hᵢ - hⱼ)² + 4)`.

In particular, the collision count `C_p(h) = 0` for all such primes.
-/
theorem excludedClasses_card_maximal {k : ℕ} {h : Fin k → ℤ}
    (hp1 : p % 4 = 1)
    (hinj : Function.Injective h)
    (hp_large : collisionThreshold h < p) :
    (excludedClasses p (fun i => (h i : ZMod p))).card = 2 * k := by
  -- Let `ν` be a root of `x² + 1 = 0` in `ZMod p`.
  obtain ⟨ν, hν⟩ : ∃ ν : ZMod p, ν ^ 2 + 1 = 0 := by
    have := @ZMod.exists_sq_eq_neg_one_iff ( p := p );
    exact Exists.elim ( this.mpr ( by linarith ) ) fun x hx => ⟨ x, by rw [ sq, ← hx ] ; ring ⟩;
  -- The excluded classes are the union of {ν - h i, -ν - h i} for each i.
  have h_union : excludedClasses p (fun i => (h i : ZMod p)) = Finset.biUnion Finset.univ (fun i => {ν - (h i : ZMod p), -ν - (h i : ZMod p)}) := by
    ext a; simp [excludedClasses];
    constructor <;> rintro ⟨ i, hi ⟩;
    · exact ⟨ i, Classical.or_iff_not_imp_left.2 fun h => mul_left_cancel₀ ( sub_ne_zero_of_ne h ) <| by linear_combination hi - hν ⟩;
    · exact ⟨ i, by rcases hi with ( rfl | rfl ) <;> linear_combination' hν ⟩;
  -- For each i, the pair {ν - h i, -ν - h i} has card 2 by single_shift_excluded_card (since p ≠ 2 as p % 4 = 1 with p prime means p ≥ 5).
  have h_card_pair : ∀ i : Fin k, ({ν - (h i : ZMod p), -ν - (h i : ZMod p)} : Finset (ZMod p)).card = 2 := by
    intro i; rw [ Finset.card_pair ] ; simp_all +decide [ sub_eq_iff_eq_add ] ;
    exact NearSquarePrimes.sqrtNegOne_ne_neg ( show p ≠ 2 by rintro rfl; contradiction ) hν;
  rw [ h_union, Finset.card_biUnion ];
  · simp_all +decide [ mul_comm ];
  · intros i hi j hj hij; simp_all +decide [ Finset.disjoint_left ] ;
    refine' ⟨ ⟨ _, _ ⟩, _, _ ⟩;
    · intro H; have := no_collision_of_large_prime_dvd ( show ( h i - h j ) ≠ 0 from sub_ne_zero_of_ne <| hinj.ne hij ) ( show ( ( h i - h j ) ^ 2 + 4 |> Int.natAbs ) < p from lt_of_le_of_lt ( Finset.le_sup ( f := fun ij : Fin k × Fin k => ( ( h ij.1 - h ij.2 ) ^ 2 + 4 |> Int.natAbs ) ) ( Finset.mk_mem_product ( Finset.mem_univ i ) ( Finset.mem_univ j ) ) ) hp_large ) ; simp_all +decide [ ← ZMod.intCast_zmod_eq_zero_iff_dvd ] ;
    · contrapose! hp_large;
      -- If `ν - h i = -ν - h j`, then `(h i - h j)² + 4 ≡ 0 (mod p)`.
      have h_collision : (h i - h j) ^ 2 + 4 ≡ 0 [ZMOD p] := by
        simp_all +decide [ ← ZMod.intCast_eq_intCast_iff ];
        grind;
      refine' le_trans _ ( Finset.le_sup ( f := fun ij : Fin k × Fin k => Int.natAbs ( ( h ij.1 - h ij.2 ) ^ 2 + 4 ) ) ( Finset.mk_mem_product ( Finset.mem_univ i ) ( Finset.mem_univ j ) ) );
      exact Nat.le_of_dvd ( Int.natAbs_pos.mpr ( by nlinarith ) ) ( Int.natCast_dvd.mp ( Int.dvd_of_emod_eq_zero h_collision ) );
    · contrapose! hp_large;
      -- If $-ν - h i = ν - h j$, then $(h i - h j)^2 + 4 ≡ 0 (mod p)$.
      have h_cong : ((h i - h j) ^ 2 + 4 : ℤ) ≡ 0 [ZMOD p] := by
        simp_all +decide [ ← ZMod.intCast_eq_intCast_iff ];
        grobner;
      refine' le_trans _ ( Finset.le_sup ( f := fun ij : Fin k × Fin k => Int.natAbs ( ( h ij.1 - h ij.2 ) ^ 2 + 4 ) ) ( Finset.mk_mem_product ( Finset.mem_univ i ) ( Finset.mem_univ j ) ) );
      exact Nat.le_of_dvd ( Int.natAbs_pos.mpr ( by nlinarith ) ) ( Int.natCast_dvd.mp ( Int.dvd_of_emod_eq_zero h_cong ) );
    · intro H;
      have := no_collision_of_large_prime_dvd ( show ( h i - h j ) ≠ 0 from sub_ne_zero_of_ne <| hinj.ne hij ) ( show ( ( h i - h j ) ^ 2 + 4 |> Int.natAbs ) < p from lt_of_le_of_lt ( Finset.le_sup ( f := fun ij : Fin k × Fin k => ( ( h ij.1 - h ij.2 ) ^ 2 + 4 |> Int.natAbs ) ) ( Finset.mk_mem_product ( Finset.mem_univ i ) ( Finset.mem_univ j ) ) ) hp_large );
      simp_all +decide [ ← ZMod.intCast_zmod_eq_zero_iff_dvd ]

end NearSquarePrimes
